version: "3.9"
services:
   database:
       image: mysql:8.0
       environment:
           MYSQL_ROOT_PASSWORD: ma
       volumes:
           - .:/var/lib/mysql
   app:
       build: .
       ports:
           - "8080:8080"
       volumes:
           - .:/usr/src/app/data
